USE DATABASE ATMOSYNC_DB;
USE SCHEMA RAW;

-- 1. Check total records
SELECT COUNT(*) AS TOTAL_RECORDS
FROM MICROCLIMATE_RAW;

-- 2. Preview records
SELECT *
FROM MICROCLIMATE_RAW
LIMIT 10;

-- 3. Check missing locations
SELECT COUNT(*) AS MISSING_LOCATION
FROM MICROCLIMATE_RAW
WHERE LOCATION IS NULL;

-- 4. Check invalid humidity
SELECT COUNT(*) AS INVALID_HUMIDITY
FROM MICROCLIMATE_RAW
WHERE HUMIDITY_PCT < 0
   OR HUMIDITY_PCT > 100;

-- 5. Check negative rainfall
SELECT COUNT(*) AS INVALID_RAINFALL
FROM MICROCLIMATE_RAW
WHERE RAINFALL_MM < 0;

-- 6. Check negative wind speed
SELECT COUNT(*) AS INVALID_WIND
FROM MICROCLIMATE_RAW
WHERE WIND_SPEED_KMPH < 0;

-- 7. Check invalid temperature relationship
SELECT COUNT(*) AS INVALID_TEMPERATURE
FROM MICROCLIMATE_RAW
WHERE TEMP_MAX_C < TEMP_MIN_C;

