USE DATABASE ATMOSYNC_DB;

-- 1. Check RAW records
SELECT
    'RAW' AS DATA_LAYER,
    COUNT(*) AS RECORD_COUNT
FROM RAW.MICROCLIMATE_RAW;

-- 2. Check dbt staging records
SELECT
    'STAGING MODEL' AS DATA_LAYER,
    COUNT(*) AS RECORD_COUNT
FROM CLEAN.STG_MICROCLIMATE;

-- 3. Check analytics records
SELECT
    'ANALYTICS' AS DATA_LAYER,
    COUNT(*) AS RECORD_COUNT
FROM CLEAN.WEATHER_SUMMARY;

-- 4. Check dashboard-ready records
SELECT
    'DASHBOARD' AS DATA_LAYER,
    COUNT(*) AS RECORD_COUNT
FROM CLEAN.DASHBOARD_WEATHER_SUMMARY;

-- 5. Preview final dashboard data
SELECT *
FROM CLEAN.DASHBOARD_WEATHER_SUMMARY
ORDER BY LOCATION
LIMIT 10;
