SELECT
    DATE,
    TRIM(LOCATION) AS LOCATION,
    LATITUDE,
    LONGITUDE,
    ELEVATION_M,
    TRIM(AREA_PROFILE) AS AREA_PROFILE,
    TEMP_MAX_C,
    TEMP_MIN_C,
    RAINFALL_MM,
    HUMIDITY_PCT,
    WIND_SPEED_KMPH,
    INGESTED_AT

FROM {{ source('raw', 'microclimate_raw') }}


USE DATABASE ATMOSYNC_DB;
USE SCHEMA CLEAN;

SELECT *
FROM STG_MICROCLIMATE
LIMIT 10;