SELECT
    LOCATION,

    COUNT(*) AS RECORD_COUNT,

    ROUND(AVG(TEMP_MAX_C), 2) AS AVG_MAX_TEMP_C,

    ROUND(AVG(TEMP_MIN_C), 2) AS AVG_MIN_TEMP_C,

    ROUND(AVG((TEMP_MAX_C + TEMP_MIN_C) / 2), 2) AS AVG_TEMP_C,

    ROUND(SUM(RAINFALL_MM), 2) AS TOTAL_RAINFALL_MM,

    ROUND(AVG(HUMIDITY_PCT), 2) AS AVG_HUMIDITY_PCT,

    ROUND(AVG(WIND_SPEED_KMPH), 2) AS AVG_WIND_SPEED_KMPH

FROM {{ ref('stg_microclimate') }}

GROUP BY LOCATION
ORDER BY LOCATION


USE DATABASE ATMOSYNC_DB;

SELECT *
FROM CLEAN.WEATHER_SUMMARY
ORDER BY LOCATION;