USE DATABASE ATMOSYNC_DB;

CREATE SCHEMA IF NOT EXISTS STAGING;

USE SCHEMA STAGING;

CREATE TABLE IF NOT EXISTS KAFKA_MICROCLIMATE_STAGING (
    DATE DATE,
    LOCATION VARCHAR(100),
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    ELEVATION_M FLOAT,
    AREA_PROFILE VARCHAR(100),
    TEMP_MAX_C FLOAT,
    TEMP_MIN_C FLOAT,
    RAINFALL_MM FLOAT,
    HUMIDITY_PCT FLOAT,
    WIND_SPEED_KMPH FLOAT,
    KAFKA_PARTITION NUMBER,
    KAFKA_OFFSET NUMBER,
    INGESTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

SELECT COUNT(*) 
FROM ATMOSYNC_DB.STAGING.KAFKA_MICROCLIMATE_STAGING;