USE DATABASE ATMOSYNC_DB;

CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS CLEAN;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;

USE SCHEMA STAGING;

SELECT
    CURRENT_DATABASE() AS DATABASE_NAME,
    CURRENT_SCHEMA() AS SCHEMA_NAME,
    CURRENT_WAREHOUSE() AS WAREHOUSE_NAME;


SHOW SCHEMAS IN DATABASE ATMOSYNC_DB;

SHOW WAREHOUSES;
SELECT CURRENT_WAREHOUSE();
