CREATE DATABASE IF NOT EXISTS ATMOSYNC_DB;

CREATE SCHEMA IF NOT EXISTS ATMOSYNC_DB.RAW;

USE DATABASE ATMOSYNC_DB;
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS MICROCLIMATE_RAW (
    DATE DATE,
    LOCATION VARCHAR(100),
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    ELEVATION_M FLOAT,
    AREA_PROFILE VARCHAR(100),
    TEMP_MAX_C FLOAT,
    TEMP_MIN_C FLOAT,
    RAINFALL_MM FLOAT,
    HUMIDITY_PCT FLOAT,
    WIND_SPEED_KMPH FLOAT,
    INGESTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

SHOW TABLES IN SCHEMA ATMOSYNC_DB.RAW;

DESC TABLE ATMOSYNC_DB.RAW.MICROCLIMATE_RAW;